### ISSUE TITLE
Ticks not explicit in the docs

### ISSUE THREAD

**Issue by jjsaunier** [Seldaek/signal-handler#1]
Hey, 

Context : php7.0 with pcntl extension enabled

This line https://github.com/Seldaek/signal-handler/blob/master/src/SignalHandler.php#L64  It's useless to tick the signal handler file itself (There is a special case that I don't get to do that?)

The tick should be declared in all php file doing long process triggered by your command

With the following example : 

``` php
        $signal = SignalHandler::create(null, function ($signal, $signalName) {
            dump('Received ' . $signalName . PHP_EOL);
        });

       $this->commandBus->handle(new LongCommandProcess([
           new Crawler1(),
           new Crawler2(),
           new Crawler3()
        ]));
```

You should decrale tick function in 4 php files (you current file, crawler1...3) to pick up the signal to  trigger your callback registered via pcntl_signal.

It's not mentioned in the docs to add `declare(ticks=1)` on all long process php file used by the command. Or people will simply think it's a bug, because signal never picked up.

**Comment by Seldaek** [comment]
Heh, interesting, is this only php7? Because I am pretty sure the code worked for me on 5.6, and the test suite passes which is curious.

**Comment by martinssipenko** [comment]
I had to add `declare(ticks = 1);` to the worker php file, in which I have `while (true) {}`.

**Comment by jjsaunier** [comment]
The test suite pass because you use pcntl_signal_dispatch() by the hand. ticks have the same behavior (when pcntl module is enabled, pcntl_signal_dispatch is registered as tick callback), on each php code block he trigger all tick callback function registered (so ticks=1 trigger is more faster to pick up the signal) so this issue is not covered by the actual test suite. 

I will create a test that failed to show that and we will see if it's specific to php7 but i'm pretty sure it's not because all php code parsed below a directive `declare` is take in account, and doesn't not change in php core between 5.x and 7.x, (like declare(strict_type=1))

**Comment by Seldaek** [comment]
OK well that would be great yes, then it's just about documenting the 
fact that the files doing the blocking loop should have declare() in 
them, unless you run php7.1 then I think we're fine.

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/signal-handler/releases/tag/1.3.0 - ticks are completely gone now, so if you upgrade please remove `declare(ticks=1);` from your code :)
