### ISSUE TITLE
declare(ticks=1) inside a condition

### ISSUE THREAD

**Issue by ninze** [Seldaek/signal-handler#6]
I was reading the docs on pcntl_async_signals  and found a comment on this page:
https://www.php.net/manual/en/control-structures.declare.php

_If anyone is trying to optionally use either pcntl_async_signals() when available (PHP >= 7.1) or ticks for older versions, this is not possible...at least not in a way that does NOT enable ticks for newer PHP versions. This is because there is simply no way to conditionally declare ticks. For example, the following will "work" but not in the way you might expect:_

    if (function_exists('pcntl_async_signals')) {
        pcntl_async_signals(true);
    } else {
        declare(ticks=1);
    }

_While signal handlers will work with this for old and new version, ticks WILL be enabled even in the case where pcntl_async_signals exists, simply because the declare statement exists._

Then I stumbled on identical code in this repo:
https://github.com/Seldaek/signal-handler/blob/main/src/SignalHandler.php#L260

**Comment by Seldaek** [comment]
Ah that's a good point, now that we target PHP 7.2+ for Composer I can do a new release here dropping the ticks then. Thanks

**Comment by Seldaek** [comment]
Closed by #7
